import { useEffect } from 'react';
import { ArrowRight, CheckCircle2, FolderOpen, LayoutDashboard, Brain, ShieldCheck } from 'lucide-react';
import { Link } from 'wouter';
import Footer from '@/components/Footer';
import { useMetaTags } from '@/lib/meta';

const steps=[
  {icon:FolderOpen,title:'Save all six downloads',body:'Keep the five specialist customer packs intact and save the Complete Home master pack alongside them.'},
  {icon:LayoutDashboard,title:'Open the master workbook or Studio',body:'Create the project brief, room register, budget position, current blockers and next three decisions.'},
  {icon:ShieldCheck,title:'Choose the shortest route',body:'Use the route map to open only the specialist pack needed for the decision that is active now.'},
  {icon:Brain,title:'Use AI with the master rule',body:'Preserve the real property, keep UNKNOWN visible, change one variable and return to measurements before approval.'},
];

export default function CompleteHomeThankYou(){
  useMetaTags({title:'Thank You | Complete Home Design System | VELUCE',description:'Getting started with the Veluce Complete Home Design System.',url:'https://velucedesign.com/thank-you/complete-home-design-system/',type:'website'});
  useEffect(()=>{const existing=document.querySelector('meta[name="robots"]') as HTMLMetaElement|null;const previous=existing?.content;const robots=existing??document.createElement('meta');if(!existing){robots.setAttribute('name','robots');document.head.appendChild(robots);}robots.setAttribute('content','noindex, nofollow, noarchive');return()=>{if(existing){if(previous)existing.setAttribute('content',previous);else existing.removeAttribute('content');}else robots.remove();};},[]);
  return <div className="min-h-screen bg-[#0c0a08] text-[#faf6ee]"><header className="border-b border-white/10"><div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-5 sm:px-8 lg:px-10"><Link href="/" asChild><a className="font-serif text-xl font-bold tracking-[0.12em] text-white">VELUCE</a></Link><span className="text-[10px] uppercase tracking-[0.2em] text-stone-500">Veluce Studio</span></div></header><main>
    <section className="relative overflow-hidden"><img src="/images/complete-home-hero.svg" alt="" className="absolute inset-0 h-full w-full object-cover opacity-35"/><div className="absolute inset-0 bg-gradient-to-b from-[#0c0a08]/55 via-[#0c0a08]/88 to-[#0c0a08]"/><div className="relative mx-auto max-w-5xl px-5 py-20 text-center sm:px-8 sm:py-28 lg:py-32"><CheckCircle2 size={40} className="mx-auto text-[#d1a86c]"/><p className="mt-6 text-[11px] uppercase tracking-[0.28em] text-[#d1a86c]">Purchase complete</p><h1 className="mx-auto mt-4 max-w-4xl font-serif text-5xl font-light leading-[1.04] text-white sm:text-6xl">You now have the whole Veluce system.</h1><p className="mx-auto mt-6 max-w-2xl text-base leading-relaxed text-stone-300 sm:text-lg">Do not try to complete every workbook. Start with the master layer, choose the shortest route for the current project, and open a specialist pack only when that decision is active.</p></div></section>
    <section className="bg-[#f5efe4] text-[#17120f]"><div className="mx-auto max-w-6xl px-5 py-16 sm:px-8 lg:px-10 lg:py-24"><p className="text-[11px] uppercase tracking-[0.28em] text-[#9b7448]">Start here</p><h2 className="mt-3 max-w-3xl font-serif text-4xl sm:text-5xl">One project. One room register. One decision trail.</h2><div className="mt-10 grid gap-4 md:grid-cols-2">{steps.map(({icon:Icon,title,body},i)=><article key={title} className="border border-[#d6c9b5] bg-[#ede3d4] p-6"><div className="flex items-center justify-between"><Icon size={22} className="text-[#9b7448]"/><span className="font-serif text-2xl text-[#9b7448]">0{i+1}</span></div><h3 className="mt-5 font-serif text-2xl">{title}</h3><p className="mt-3 text-sm leading-relaxed text-stone-700">{body}</p></article>)}</div></div></section>
    <section className="bg-[#17130f]"><div className="mx-auto max-w-5xl px-5 py-16 text-center sm:px-8 lg:py-24"><p className="text-[11px] uppercase tracking-[0.28em] text-[#d1a86c]">The Veluce Path</p><p className="mx-auto mt-4 max-w-4xl font-serif text-3xl leading-snug text-white sm:text-4xl">Reality → Direction → Space → Light → Buy → Live</p><p className="mx-auto mt-5 max-w-2xl text-sm leading-relaxed text-stone-400">If a fixed constraint is still UNKNOWN, do not move it downstream and hope the next stage fixes it.</p></div></section>
    <section className="bg-[#0c0a08]"><div className="mx-auto max-w-5xl px-5 py-16 text-center sm:px-8 lg:py-24"><h2 className="font-serif text-4xl text-white sm:text-5xl">Keep exploring Veluce.</h2><p className="mx-auto mt-5 max-w-2xl text-sm leading-relaxed text-stone-400">The journal remains the inspiration and research layer around the paid Studio systems.</p><div className="mt-8"><Link href="/articles" asChild><a className="inline-flex items-center gap-2 rounded-sm bg-[#f5efe4] px-5 py-3 text-xs font-semibold uppercase tracking-[0.14em] text-[#17120f] hover:bg-white">Browse the journal <ArrowRight size={15}/></a></Link></div></div></section>
  </main><Footer/></div>;
}
